### 레이어 : 신경망 기본 블록

In [1]:
import torch
from torch.nn import Linear, ReLU
import torch.nn as nn
import numpy as np
from torch.autograd import Variable

In [2]:
myLayer = Linear(in_features=10,out_features=5,bias=True)
inp = Variable(torch.randn(1,10))
myLayer = Linear(in_features=10,out_features=5,bias=True) 
myLayer(inp)

tensor([[-0.1777,  0.3403,  0.8386,  0.0689,  0.8562]],
       grad_fn=<AddmmBackward>)

In [3]:
myLayer.weight

Parameter containing:
tensor([[ 0.2321,  0.1621, -0.0300,  0.2222, -0.0999, -0.2859,  0.0331, -0.0697,
          0.0604, -0.0679],
        [ 0.2236, -0.2986,  0.2389, -0.1634, -0.0815, -0.2885,  0.2693, -0.1172,
         -0.0194,  0.0451],
        [ 0.0444, -0.0641,  0.0274,  0.2575, -0.0494,  0.2635, -0.0458,  0.1255,
          0.2358,  0.1845],
        [ 0.0250, -0.0894,  0.0819, -0.2266,  0.1136, -0.0992, -0.1700,  0.0077,
         -0.0456, -0.2411],
        [ 0.0959, -0.0887,  0.3078,  0.1841, -0.2191,  0.0465, -0.0213,  0.0794,
         -0.2825,  0.0990]], requires_grad=True)

In [4]:
myLayer.bias

Parameter containing:
tensor([-0.2552,  0.2485,  0.1324,  0.2636, -0.1519], requires_grad=True)

### 선형 레이어 쌓기

In [5]:
myLayer1 = Linear(10,5)
myLayer2 = Linear(5,2)
myLayer2(myLayer1(inp))

tensor([[0.2977, 0.2996]], grad_fn=<AddmmBackward>)

### PyTorch 비선형 활성함수

In [6]:
sample_data = Variable(torch.Tensor([[1,2,-1,-1]])) 
myRelu = ReLU()
myRelu(sample_data)


tensor([[1., 2., 0., 0.]])

In [7]:
import torch.nn as nn
import torch.nn.functional as F
sample_data = Variable(torch.Tensor([[1,2,-1,-1]])) 
f = F.relu(sample_data) # Much simpler.
f

tensor([[1., 2., 0., 0.]])

### 신경망

In [8]:
class MyFirstNetwork(nn.Module):
    def __init__(self,input_size,hidden_size,output_size):
        super(MyFirstNetwork,self).__init__() 
        self.layer1 = nn.Linear(input_size,hidden_size) 
        self.layer2 = nn.Linear(hidden_size,output_size)
    def __forward__(self,input): 
        out = self.layer1(input) 
        out = nn.ReLU(out)
        out = self.layer2(out) 
        return out

### 오차(Loss)

In [9]:
loss = nn.MSELoss()
input = Variable(torch.randn(3, 5), requires_grad=True) 
target = Variable(torch.randn(3, 5))
output = loss(input, target)
output.backward()

In [10]:
def cross_entropy(true_label, prediction):
    if true_label == 1:
        return -log(prediction)
    else:
        return -log(1 - prediction)

In [11]:
loss = nn.CrossEntropyLoss()
input = Variable(torch.randn(3, 5), requires_grad=True) 
target = Variable(torch.LongTensor(3).random_(5)) 
output = loss(input, target)
output.backward()

### 옵티마이저

- 예제 코드
```
# 데모 용
import torch.optim as optim
optimizer = optim.SGD(model.parameters(), lr = 0.01)
for input, target in dataset:
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output, target)
    loss.backward()
    optimizer.step()
```